In [36]:
import pandas as pd
import numpy as np

data = {
    'Student_ID': [101, 102 , 103, 104, 105, 105,106],
    'Name': ['Alice ', 'bob', 'Charlie', 'Daisy', 'Ethan', 'Ethan', 'Frank'], # Typos/spaces
    'Subject': ['Math', 'Science', 'Math', 'History', 'Science', 'Science', 'UNKNOWN'], # Missing value string
    'Score': [85.0, np.nan, 92.0, -10.0, 45.0, 45.0, 88.0], # NaN and an impossible negative score
    'Passed': ['True', 'False', 'TRUE', 'True', 'False', 'False', 'UNKNOWN'] # Inconsistent text
}

df_data = pd.DataFrame(data)
df_data

   Student_ID     Name  Subject  Score   Passed
0         101   Alice      Math   85.0     True
1         102      bob  Science    NaN    False
2         103  Charlie     Math   92.0     TRUE
3         104    Daisy  History  -10.0     True
4         105    Ethan  Science   45.0    False
5         105    Ethan  Science   45.0    False
6         106    Frank  UNKNOWN   88.0  UNKNOWN

In [37]:
#removing duplicates
df_data = df_data.drop_duplicates()

In [38]:
#cleaning string
df_data['Name'] = df_data['Name'].str.strip().str.capitalize()

In [39]:
#fixing outliers
df_data.loc[df_data['Score'] < 0, 'Score'] = np.nan

In [40]:
#handling missing values
mean_score = df_data['Score'].mean()
df_data['Score'] = df_data['Score'].fillna(mean_score)

In [41]:
#standardizing text values
df_data['Passed'] = df_data['Passed'].astype(str).str.upper()
df_data['Passed'] = df_data['Passed'].replace('UNKNOWN', 'FALSE')

In [46]:
#replace specific text errors
df_data['Subject'] = df_data['Subject'].astype(str).str.upper()
df_data['Subject'] = df_data['Subject'].replace('UNKNOWN', 'ENGLISH')

In [45]:
median_value = df_data['Student_ID'].median()
#FillING the missing cells with that median
df_data['Student_ID'] = df_data['Student_ID'].fillna(median_value)
df_data

   Student_ID     Name  Subject  Score Passed
0         101    Alice     Math   85.0   TRUE
1         102      Bob  Science   77.5  FALSE
2         103  Charlie     Math   92.0   TRUE
3         104    Daisy  History   77.5   TRUE
4         105    Ethan  Science   45.0  FALSE
6         106    Frank  English   88.0  FALSE

In [42]:
median_value = df_data['Student_ID'].median()
# 2. Fill the missing cells with that median
df_data['Student_ID'] = df_data['Student_ID'].fillna(median_value)
df_data

   Student_ID     Name  Subject  Score Passed
0         101    Alice     Math   85.0   TRUE
1         102      Bob  Science   77.5  FALSE
2         103  Charlie     Math   92.0   TRUE
3         104    Daisy  History   77.5   TRUE
4         105    Ethan  Science   45.0  FALSE
6         106    Frank  UNKNOWN   88.0  FALSE